### ISSUE TITLE
Issue when using kobo_prepare_form

### ISSUE THREAD

**Issue by salvarezb** [Edouard-Legoupil/kobocruncher#8]
Hi, I'm new to this package. When trying to use the kobo_prepare_form function I get the following error:

[1] "There was an error in the xlsform preparation step!!! \n\n"
$message
[1] "replacement has 0 rows, data has 319"

$call
`$<-.data.frame`(`*tmp*`, "label.lenght", value = integer(0))

attr(,"class")
[1] "try-error"

I followed all the steps shown in the tutorial but I still cant fix this error. I was wondering if someone could help me.

**Comment by Edouard-Legoupil** [comment]
Hello ! Maybe you can share the xlsform directly  to double check - legoupil-at-unhcr.org - but very likely this is because you have not documented the language parameter - so the function is not able to tell which language to use to build the data dictionary - see https://edouard-legoupil.github.io/kobocruncher/tutorial/02-Relabeling.html#7
